name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  mongo_dart: ^0.10.0
  fluttertoast: ^8.2.4
  uuid: ^4.2.2
  flutter_datetime_picker_plus: ^2.1.0
  intl: ^0.19.0
  http: ^0.13.6
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  google_maps_flutter: ^2.5.3
  dio: ^5.4.3+1
  flutter_polyline_points: ^1.0.0
  location: ^5.0.3
  flutter_paypal: ^0.2.0
  flutter_paypal_checkout: ^1.0.1
  firebase_messaging: ^14.7.1
  flutter_local_notifications: ^9.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
  - assets/page-1/images/GioiThieu.png
  - assets/page-1/images/thanh-pham-1120-1.png
  - assets/page-1/images/thanh-pham-1120-1-ENb.png
  - assets/page-1/images/thanh-pham-1120-1-TZR.png
  - assets/page-1/images/thanh-pham-1120-1-Z8K.png
  - assets/page-1/images/iconoir-coins.png
  - assets/page-1/images/thanh-pham-1120-1-XHq.png
  - assets/page-1/images/thanh-pham-1120-1-3hy.png
  - assets/page-1/images/thanh-pham-1120-1-EAj.png
  - assets/page-1/images/vector.png
  - assets/page-1/images/rectangle-11.png
  - assets/page-1/images/premium-vector-iced-taiwan-or-japan-bubble-tea-milk-tea-or-matcha-green-tea-1.png
  - assets/page-1/images/shopping-cart.png
  - assets/page-1/images/thanh-pham-1120-1-dbd.png
  - assets/page-1/images/thanh-pham-1120-1-8oH.png
  - assets/page-1/images/home.png
  - assets/page-1/images/group.png
  - assets/page-1/images/rectangle-8.png
  - assets/page-1/images/facebook-1.png
  - assets/page-1/images/rectangle-30.png
  - assets/page-1/images/vector-8CF.png
  - assets/page-1/images/home-1SP.png
  - assets/page-1/images/thanh-pham-1120-1-xiK.png
  - assets/page-1/images/premium-vector-iced-taiwan-or-japan-bubble-tea-milk-tea-or-matcha-green-tea-1-be7.png
  - assets/page-1/images/premium-vector-iced-taiwan-or-japan-bubble-tea-milk-tea-or-matcha-green-tea-1-WFH.png
  - assets/page-1/images/thanh-pham-1120-1-rdu.png
  - assets/page-1/images/thanh-pham-1120-1-7Jw.png
  - assets/page-1/images/group-plus.png
  - assets/page-1/images/thanh-pham-1120-1-a7H.png
  - assets/page-1/images/thanh-pham-1120-1-RXD.png
  - assets/page-1/images/thanh-pham-1120-1-sE7.png
  - assets/page-1/images/thanh-pham-1120-1-HFD.png
  - assets/page-1/images/premium-vector-iced-taiwan-or-japan-bubble-tea-milk-tea-or-matcha-green-tea-1-gAs.png
  - assets/page-1/images/arrow-back-rounded.png
  - assets/page-1/images/vector-bKm.png
  - assets/page-1/images/ios-elements.png
  - assets/page-1/images/vector-K6X.png
  - assets/page-1/images/rectangle-12.png
  - assets/page-1/images/search.png
  - assets/page-1/images/premium-vector-iced-taiwan-or-japan-bubble-tea-milk-tea-or-matcha-green-tea-1-heo.png
  - assets/page-1/images/rectangle-8-xjh.png
  - assets/page-1/images/group-plus-ZTD.png
  - assets/page-1/images/premium-vector-iced-taiwan-or-japan-bubble-tea-milk-tea-or-matcha-green-tea-1-CY7.png
  - assets/page-1/images/thanh-pham-1120-1-oNo.png
  - assets/page-1/images/user-solid.png
  - assets/page-1/images/premium-vector-iced-taiwan-or-japan-bubble-tea-milk-tea-or-matcha-green-tea-1-x5D.png
  - assets/page-1/images/arrow-back-rounded-VL3.png
  - assets/page-1/images/ios-elements-GZ5.png
  - assets/page-1/images/thanh-pham-1120-1-deX.png
  - assets/page-1/images/notifications.png
  - assets/page-1/images/favorite-outline.png
  - assets/page-1/images/group-plus-zUP.png
  - assets/page-1/images/ellipse-9.png
  - assets/page-1/images/water-full-rounded.png
  - assets/page-1/images/home-BuZ.png
  - assets/page-1/images/premium-vector-iced-taiwan-or-japan-bubble-tea-milk-tea-or-matcha-green-tea-1-uqZ.png
  - assets/page-1/images/rectangle-9.png
  - assets/page-1/images/group-header.png
  - assets/page-1/images/check-circle.png
  - assets/page-1/images/thanh-pham-1120-1-zBR.png
  - assets/page-1/images/vector-RCB.png
  - assets/page-1/images/rectangle-29.png
  - assets/page-1/images/group-plus-z4F.png
  - assets/page-1/images/vector-KEw.png
  - assets/page-1/images/ios-elements-GBR.png
  - assets/page-1/images/ios-elements-1wd.png
  - assets/page-1/images/user-solid-cTZ.png
  - assets/page-1/images/thanh-pham-1120-1-Hqq.png
  - assets/page-1/images/vector-36F.png
  - assets/page-1/images/group-plus-52F.png
  - assets/page-1/images/vector-fwM.png
  - assets/page-1/images/clarity-car-solid.png
  - assets/page-1/images/shopping-cart-BXd.png
  - assets/page-1/images/ellipse-9-Yis.png
  - assets/page-1/images/rectangle-32.png
  - assets/page-1/images/group-plus-a71.png
  - assets/page-1/images/ios-elements-mwV.png
  - assets/page-1/images/ios-elements-oY3.png
  - assets/page-1/images/thanh-pham-1120-1-CkX.png
  - assets/page-1/images/google-1.png
  - assets/page-1/images/rectangle-10.png
  - assets/page-1/images/check-circle-ENB.png
  - assets/page-1/images/group-plus-5vP.png
  - assets/page-1/images/home-pqM.png
  - assets/page-1/images/thanh-pham-1120-1-BsD.png
  - assets/page-1/images/vector-Wsy.png
  - assets/page-1/images/settings-outline-rounded.png
  - assets/page-1/images/solar-letter-broken.png
  - assets/page-1/images/arrow-back-rounded-HmZ.png
  - assets/page-1/images/home-krj.png
  - assets/page-1/images/home-QUX.png
  - assets/page-1/images/water-full-rounded-qNo.png
  - assets/page-1/images/user-solid-snf.png
  - assets/page-1/images/ellipse-9-Pvf.png
  - assets/page-1/images/water-full-rounded-Fa7.png
  - assets/page-1/images/shopping-cart-rxo.png
  - assets/page-1/images/ellipse-9-RCb.png
  - assets/page-1/images/group-plus-bPu.png
  - assets/page-1/images/arrow-back-rounded-nhD.png
  - assets/page-1/images/home-aaj.png
  - assets/page-1/images/water-full-rounded-jcT.png
  - assets/page-1/images/ios-elements-QVd.png
  - assets/page-1/images/ellipse-12-bg.png
  - assets/page-1/images/ellipse-10-bg.png
  - assets/page-1/images/icon-eye-outline.png
  - assets/page-1/images/arrow-back-rounded-BR9.png
  - assets/page-1/images/thanh-pham-1120-1-rGP.png
  - assets/page-1/images/ios-elements-nfq.png
  - assets/page-1/images/home-9WP.png
  - assets/page-1/images/arrow-back-rounded-Tyy.png
  - assets/page-1/images/home-ioR.png
  - assets/page-1/images/vector-obm.png
  - assets/page-1/images/ios-elements-1Qs.png
  - assets/page-1/images/home-17M.png
  - assets/page-1/images/arrow-back-rounded-k4w.png
  - assets/page-1/images/thanh-pham-1120-1-5kb.png
  - assets/page-1/images/check-circle-vab.png
  - assets/page-1/images/ios-elements-NeT.png
  - assets/page-1/images/rectangle-9-RBu.png
  - assets/page-1/images/rectangle-12-CYF.png
  - assets/page-1/images/rectangle-12-W8F.png
  - assets/page-1/images/rectangle-11-PeP.png
  - assets/page-1/images/rectangle-8-LbZ.png
  - assets/page-1/images/rectangle-11-bg.png
  - assets/page-1/images/rectangle-9-EFR.png
  - assets/page-1/images/rectangle-9-8MV.png
  - assets/page-1/images/rectangle-8-Lj1.png
  - assets/page-1/images/rectangle-10-NBq.png
  - assets/page-1/images/rectangle-9-bg.png
  - assets/page-1/images/rectangle-10-bg.png
  - assets/page-1/images/rectangle-10-Jgf.png
  - assets/page-1/images/rectangle-11-ffM.png
  - assets/page-1/images/rectangle-8-uQb.png
  - assets/page-1/images/rectangle-11-tzK.png
  - assets/page-1/images/rectangle-8-bg.png
  - assets/page-1/images/rectangle-8-jd1.png
  - assets/page-1/images/rectangle-8-G79.png
  - assets/page-1/images/rectangle-11-rRV.png
  - assets/page-1/images/rectangle-12-j5q.png
  - assets/page-1/images/rectangle-10-rgF.png
  - assets/page-1/images/rectangle-9-CEK.png
  - assets/page-1/images/rectangle-12-a5D.png
  - assets/page-1/images/rectangle-9-xkX.png
  - assets/page-1/images/rectangle-10-bTd.png
  - assets/page-1/images/rectangle-8-vym.png
  - assets/page-1/images/rectangle-11-SSK.png
  - assets/page-1/images/rectangle-8-SpP.png
  - assets/page-1/images/rectangle-8-mXD.png
  - assets/page-1/images/rectangle-8-vf1.png
  - assets/page-1/images/rectangle-12-Fyh.png
  - assets/page-1/images/rectangle-10-zRV.png
  - assets/page-1/images/rectangle-8-MWw.png
  - assets/page-1/images/rectangle-8-3eo.png
  - assets/page-1/images/rectangle-12-67h.png
  - assets/page-1/images/rectangle-8-miP.png
  - assets/page-1/images/rectangle-12-gNB.png
  - assets/page-1/images/imageIosElements_14824.png
  - assets/page-1/images/imageEllipse_14129.png
  - assets/page-1/images/imageWaterFullRounded_126135.png
  - assets/page-1/images/imageEventNote_126157.png
  - assets/page-1/images/imageSupervisedUserCircle_126147.png
  - assets/page-1/images/imageInfoRounded_126164.png
  - assets/page-1/images/imageGroupIcsearch_126180.png
  - assets/page-1/images/imageArrowBackRounded_126174.png
  - assets/page-1/images/imageVector_131211.png
  - assets/page-1/images/imageGroupIcsearch_126180.png
  - assets/page-1/images/imageVector_131211.png
  - assets/page-1/images/containerGroupAddproImageVector_131208.png
  - assets/page-1/images/containerEllipse_153372.png
  - assets/page-1/images/containerGroup_16836.png
  - assets/page-1/images/imageVector_166441.png
  - assets/page-1/images/Editbtn.png
  - assets/page-1/images/delete.png
  - assets/page-1/images/avt 1.png
  - assets/page-1/images/imageGroup_148124.png
  - assets/page-1/images/imageEllipse_14129.png
  - assets/page-1/images/imageRectangle_148130.png
  - assets/page-1/images/imageRectangle_152165.png
  - assets/page-1/images/imageRectangle_148120.png
  - assets/page-1/images/imageWaterFullRounded_126135.png
  - assets/page-1/images/Group Plus.png
  - assets/page-1/images/thanhtoanthanhcong.png
  - assets/page-1/images/Minus1.png
  - assets/page-1/images/plusSP.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  - flutter:
      fonts:
        - family: TimesNewRoman
          fonts:
            - asset: fonts/Times_New_Roman.ttf

