// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCqWyTUWrY_V30Eu1G-_9V0cjdKPtOzsk',
    appId: '1:962204953791:web:4b71a30e70493ac4996a0a',
    messagingSenderId: '962204953791',
    projectId: 'flutter-3253e',
    authDomain: 'flutter-3253e.firebaseapp.com',
    storageBucket: 'flutter-3253e.appspot.com',
    measurementId: 'G-410K65ZTZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_fnLt7MokDuPUdCeacQkFdIFDl7rA47w',
    appId: '1:962204953791:android:50888e246ab2c1bd996a0a',
    messagingSenderId: '962204953791',
    projectId: 'flutter-3253e',
    storageBucket: 'flutter-3253e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaeU2xsYa496y27UcW2SyRGE0m0uXh3JA',
    appId: '1:962204953791:ios:1d3c8fa8d5d1ec38996a0a',
    messagingSenderId: '962204953791',
    projectId: 'flutter-3253e',
    storageBucket: 'flutter-3253e.appspot.com',
    iosClientId: '962204953791-g92i3f02s21okegijur3np0avf64uhff.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaeU2xsYa496y27UcW2SyRGE0m0uXh3JA',
    appId: '1:962204953791:ios:1d3c8fa8d5d1ec38996a0a',
    messagingSenderId: '962204953791',
    projectId: 'flutter-3253e',
    storageBucket: 'flutter-3253e.appspot.com',
    iosClientId: '962204953791-g92i3f02s21okegijur3np0avf64uhff.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
